### ISSUE TITLE
Time Issue

### ISSUE THREAD

**Issue by theanubhavk** [cubicbyte/tempmail-python#1]
**I really enjoyed this tool,but there's something that i think make this tool more impressive is to reduce the time delay to recieve the mail.**

**Comment by cubicbyte** [comment]
Fair enough. I'll reduce the inbox check interval to 200ms and will add the ability to configure this

**Comment by theanubhavk** [comment]
> Fair enough. I'll reduce the inbox check interval to 200ms and will add the ability to configure this

Thank you
