### ISSUE TITLE
Is this project live?

### ISSUE THREAD

**Issue by ghltshubh** [cubicbyte/tempmail-python#10]

**Comment by cubicbyte** [comment]
Of course! There are no updates because there is no need for them now

**Comment by ghltshubh** [comment]
But it doesn't work

**Comment by cubicbyte** [comment]
Just checked, it's working

Make sure you're using latest python, pip and library version. Or even better send the error you're getting

**Comment by Happ1ness-dev** [comment]
Can confirm, works perfectly for me too
