### ISSUE TITLE
Getting issue while fetching mail id

### ISSUE THREAD

**Issue by nitinkumar30** [cubicbyte/tempmail-python#7]
<img width="848" alt="image" src="https://github.com/cubicbyte/tempmail-python/assets/40369168/dc528e8d-be91-4626-8b16-cead602a59f6">

Getting error while splitting mail ID from gmail.

```
username, domain = address.split('@')
    ^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

Kindly check this. Getting subject and body of mail but just username or mail id from where mail is coming is not getting.

**Comment by nitinkumar30** [comment]
> <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/40369168/333785880-dc528e8d-be91-4626-8b16-cead602a59f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA5MDEsIm5iZiI6MTcxNjY0MDYwMSwicGF0aCI6Ii80MDM2OTE2OC8zMzM3ODU4ODAtZGM1MjhlOGQtYmU5MS00NjI2LThiMTYtY2VhZDYwMmE1OWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEyMzY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYTY2OTAyN2JlZTc0MWZhMzUxNGJhNzQyY2Q4OTU5ZDU4MzIyMjQxZmQ2ODdlNWNjYjM3NTBhZDQ0MDM4NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zRR_D_G5ZMY7Qa_4G2thiJy-fMVanY4BfqUk7M3I31I">
> Getting error while splitting mail ID from gmail.
> 
> ```
> username, domain = address.split('@')
>     ^^^^^^^^^^^^^^^^
> ValueError: not enough values to unpack (expected 2, got 1)
> ```
> 
> Kindly check this. Getting subject and body of mail but just username or mail id from where mail is coming is not getting.

This code is wrong. It checks body of mail as address, but it should include mail id. Check this code in providers.py file

<img width="461" alt="image" src="https://github.com/cubicbyte/tempmail-python/assets/40369168/ed8066ad-1513-4184-b16e-1f41790423a7">

This is the output I'm getting while printing the address.

<img width="236" alt="image" src="https://github.com/cubicbyte/tempmail-python/assets/40369168/110a1d42-d6de-4404-b57d-2eea26fdd97c">

**Comment by cubicbyte** [comment]
Hi, seems like you're using the library incorrectly.

In this line:

```python
email = EMail(msg.body)
```

You are trying to pass `msg.body` to `EMail`, but EMail only accepts address (example@mail.com)
